### ISSUE TITLE
Provide screenshots

### ISSUE THREAD

**Issue by ppoektos** [brunofonseca/redmine_issue_templates_notes#1]
Please provide several screenshots that could explain plugin's functionality.

**Comment by brunofonseca** [comment]
Hi, will arrange the fastest possible screens.

**Comment by brunofonseca** [comment]
Hy ppoektos!

The guide for using the plugin can be found in the link :

https://github.com/brunofonseca/redmine_issue_templates_notes/wiki/Redmine-Issue-Templates-Notes-Usage-Guide
