### ISSUE TITLE
Version incompatible with Redmine 3.3.2

### ISSUE THREAD

**Issue by aceccarelli** [brunofonseca/redmine_issue_templates_notes#4]
Hi!

On Redmine 3.3.2 presented the error below

I will be grateful if you correct and leave a version compatible with redmine 3.X

Thanks!

<pre>
template-debian:/home/redmine332/plugins# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /home/redmine332)
An error occurred while loading the routes definition of redmine_issue_templates_notes plugin (/home/redmine332/plugins/redmine_issue_templates_notes/config/routes.rb): You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action".
</pre>

**Comment by brunofonseca** [comment]
Hi, aceccarelli, how's it going?

We already have a migration plan to use the plugin in the new version mentioned, but not yet planned for release.

Thanks for the feedback .

**Comment by aceccarelli** [comment]
look at this - https://github.com/subaru019/redmine_issue_templates_notes
