### ISSUE TITLE
Can't insert note templates

### ISSUE THREAD

**Issue by dkastl** [brunofonseca/redmine_issue_templates_notes#6]
Eventually this is a compatibility issue with Redmine 3.4.
I'm not able to add template notes. See the following screenshots:

![screenshot from 2017-08-13 21-12-21](https://user-images.githubusercontent.com/227762/29249545-a6347e48-8031-11e7-8a9f-d90b2396be4e.png)
![screenshot from 2017-08-13 21-12-37](https://user-images.githubusercontent.com/227762/29249546-a673d9f8-8031-11e7-8313-7b81907f1570.png)

I'm using `redmine-3.3` branch and the following environment.
```
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.4.1-p111 (2017-03-22) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    development
  Database adapter               PostgreSQL
```
Do you have an idea, why this can happen?

**Comment by brunofonseca** [comment]
Hi @dkastl!

Thanks for the remarks. This happened because the validation is wrong. I get to fix the problem anyway anyway.

The branch is rm-3.1.7. Including, this question is verified in this case.

Wait for respective correction.

Thanks.
