### ISSUE TITLE
Redmine 3.4.8.stable.17840 shows "loading ..." and cannot select note template

### ISSUE THREAD

**Issue by zuoliang365** [brunofonseca/redmine_issue_templates_notes#8]
Hi, thanks for your great work.
I tried to install issue_templates_notes in Redmine 3.4.8. 
But when I enable the module, open issue, the web page show "loading ..." always, and click "replay", cannot select any note template.
Would you update this project for Redmine new version?
Thanks a lot!

**Comment by brunofonseca** [comment]
Hi @zuoliang365 !
Thanks for feedback and sorry for the delay time on response. 
Yeah! I'm working on this now!
On the next weeks , new updates haven released.
